In [ ]:
!pip3 install pandas

In [9]:
import os
print(os.getcwd())

/Users/karthikeyan/Documents/news_popularity_system/Notebook

In [28]:
import pandas as pd

df = pd.read_csv("/Users/karthikeyan/Documents/news_popularity_system/data/News_dataset.csv")

print(df.shape)

df.head()

df.info()

(216900, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216900 entries, 0 to 216899
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Title        216900 non-null  object
 1   Description  216885 non-null  object
dtypes: object(2)
memory usage: 3.3+ MB

In [29]:
df["Combined_text"] = df["Title"] + "   " + df["Description"]

df.head()

,Title,Description,Combined_text
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...,Obama Lays Wreath at Arlington National Cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit...",A Look at the Health of the Chinese Economy ...
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at...",Nouriel Roubini: Global Economy Not Back to 20...
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...,Finland GDP Expands In Q4 Finland's economy ...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...,"Tourism, govt spending buoys Thai economy in J..."

In [30]:
# Remove rows with missing Description
df = df.dropna(subset=["Description"])

# Reset index after dropping
df = df.reset_index(drop=True)

df.shape

(216885, 3)

In [31]:
df.sample(5000)

,Title,Description,Combined_text
35173,"India Says Economy Grew 7.3 Percent in Q3, Sur...",India says its economy grew 7.3 percent in the...,"India Says Economy Grew 7.3 Percent in Q3, Sur..."
214290,Mets Bracing for Beginning of Martnez Era,"Pedro Martnez took the M.R.I., passed the phys...",Mets Bracing for Beginning of Martnez Era Pe...
192639,Oracle moves to quarterly patch release schedule,"NOVEMBER 18, 2004 (COMPUTERWORLD) - Oracle Cor...",Oracle moves to quarterly patch release schedu...
34512,Top euro zone economy forecaster optimistic on...,The recent pickup in euro zone economic growth...,Top euro zone economy forecaster optimistic on...
175446,Second group claims bombing,A PREVIOUSLY unheard of militant group claimed...,Second group claims bombing A PREVIOUSLY unh...
...,...,...,...
179441,Saskatchewan court rules traditional definitio...,Canadian Press - SASKATOON (CP) - Saskatchewan...,Saskatchewan court rules traditional definitio...
92180,Mariners torment old foe A #39;s,"Ichiro, Madritsch and Cabrera are having a bla...","Mariners torment old foe A #39;s Ichiro, Mad..."
57091,Obama holding tax reform hostage: Norquist,"On Wednesday, Pfizer and Allergan announced th...",Obama holding tax reform hostage: Norquist O...
39306,What the circular economy means for battery re...,Because the circular economy advocates a broad...,What the circular economy means for battery re...
8672,Obama Exceeds 3-Minute Speaking Limit at Clima...,President Barack Obama was one of three speake...,Obama Exceeds 3-Minute Speaking Limit at Clima...

15